### ISSUE TITLE
Jako klient chcę wyświetlić aktualne zamówienia, aby wiedzieć jakich posiłków mam się spodziewać

### ISSUE THREAD

**Issue by aidian3k** [aidian3k/caterly#11]
<img width="643" alt="Image" src="https://github.com/user-attachments/assets/ddc262b4-55a6-45ba-9112-ac96f0379e85" />

**Comment by martynaskowronska** [comment]
[BE] https://github.com/aidian3k/caterly/issues/118 - Mateusz Skoczek
[FE] https://github.com/aidian3k/caterly/issues/119 - Marcin Kowalski
