### ISSUE TITLE
Jako klient chcę mieć możliwość wyświetlenia historycznych zamówień

### ISSUE THREAD

**Issue by aidian3k** [aidian3k/caterly#13]
<img width="604" alt="Image" src="https://github.com/user-attachments/assets/0b522013-9453-4bbf-aae0-312504b20af6" />

**Comment by martynaskowronska** [comment]
[BE]  - https://github.com/aidian3k/caterly/issues/122 - Czarek
[FE] - https://github.com/aidian3k/caterly/issues/123 - Kuba
