### ISSUE TITLE
Jako klient chcę mieć możliwość dodania opinii o zamówieniu, aby ocenić dokonane zamówienie

### ISSUE THREAD

**Issue by aidian3k** [aidian3k/caterly#15]
<img width="614" alt="Image" src="https://github.com/user-attachments/assets/7e05ccd3-5040-41b3-af60-24faba68a46e" />

**Comment by martynaskowronska** [comment]
[BE] - https://github.com/aidian3k/caterly/issues/126 - Karol
[FE] - https://github.com/aidian3k/caterly/issues/127 - Adam
