### ISSUE TITLE
Jako klient chce wyświetlić szczegóły zamówienia

### ISSUE THREAD

**Issue by aidian3k** [aidian3k/caterly#16]
<img width="605" alt="Image" src="https://github.com/user-attachments/assets/13421856-85c2-4ff9-a1de-30f8a3205015" />

**Comment by martynaskowronska** [comment]
[BE] - https://github.com/aidian3k/caterly/issues/124 - Dawid
[FE] - https://github.com/aidian3k/caterly/issues/125 - Igor
