### ISSUE TITLE
Jako firma kateringowa chcę wyświetlić listy własnych ofert katernigowych, aby sprawdzić aktualną ofertę

### ISSUE THREAD

**Issue by aidian3k** [aidian3k/caterly#29]
<img width="343" alt="image" src="https://github.com/user-attachments/assets/2a372947-fef4-43ee-89d1-08668034ef00">

**Comment by KubaOrz** [comment]
Done
![Zrzut ekranu z 2024-11-20 22-35-18](https://github.com/user-attachments/assets/51a16340-4e6e-44de-a974-0fed49279177)
