### ISSUE TITLE
Jako firma kateringowa chcę mieć możliwość dodania nowego posiłku do oferty, aby klient mógł złożyć zamówienie na nowy posiłek

### ISSUE THREAD

**Issue by aidian3k** [aidian3k/caterly#31]
<img width="694" alt="image" src="https://github.com/user-attachments/assets/d7f44545-d632-4cda-adf5-17ee1bd007e6">

**Comment by StanislawMalinski** [comment]
![Screenshot 2024-10-18 at 21 11 11](https://github.com/user-attachments/assets/5a343721-6681-4d43-8ba8-7e28a7df22c5)
