### ISSUE TITLE
Jako klient chce złożyć zamówienie posiłku, aby zakupić posiłek

### ISSUE THREAD

**Issue by aidian3k** [aidian3k/caterly#8]
<img width="609" alt="Image" src="https://github.com/user-attachments/assets/514340a8-5cd8-49fd-a1cb-0607150e3243" />

**Comment by martynaskowronska** [comment]
[BE] https://github.com/aidian3k/caterly/issues/120
[FE] https://github.com/aidian3k/caterly/issues/121 - Stanisław Malinowski
